config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :slides
  get 'admin/dashboard'

  devise_for :users
  
  get 'orders/create'

  resources :products
  #resources :users
  resources :orders

  root 'pages#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  post '/cart/add' => 'cart#add'

  get '/sincronizar' => 'products#sincronizar'
  get '/sincronizarupdate' => 'products#sincronizarupdate'
  get '/dashboard' => 'admin#dashboard'
  get '/cuenta' => 'pages#account'
  get '/verificar' => 'pages#verificar'
  get '/newcustomer' => 'pages#newcustomer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, SlideUploader
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:link, :image, :title)
    end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(slide) do |f| %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :link %>
    <%= f.url_field :link, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label "Imagen" %>
    <%= f.file_field :image, :class => "form-control", :required => true %>
  </div>

    <%#= f.label :title %>
    <%#= f.text_field :title %>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<div class="container">
  <h1>Editar Slide</h1>
  <div class="row">
    <div class="col-12 col-sm-4 mb-3">
      <%= render 'form', slide: @slide %>
    </div>
    <div class="col-12 col-sm-8">
      <%= image_tag @slide.image.url, :class => "img-fluid" %>
    </div>
  </div>
  <%= link_to 'Atrás', slides_path %>
</div>

app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Slides</h1>

  <%= link_to 'Agregar Slide', new_slide_path, :class => "btn btn-primary" %>

  <% @slides.each do |slide| %>
    <div class="row my-2">
      <div class="col-10">
        <%= link_to slide.link do %>
          <%= image_tag slide.image.url, :class => "img-fluid" %>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to '', edit_slide_path(slide), :class => "fa fa-pencil btn btn-warning" %>
        <%= link_to '', slide, :class => "fa fa-trash-o btn btn-danger", method: :delete, data: { confirm: 'Estás seguro que quieres eliminar este slide?' } %>
      </div>
    </div>
  <% end %>
  
</div>

app/views/slides/new.html.erb
<div class="container">
  <h1>Agregar Slide</h1>
  <div class="row mt-3">
    <div class="col-12 col-sm-4">
      <%= render 'form', slide: @slide %>
    </div>
    <div class="col-12 col-sm-8">
      
    </div>
  </div>
  <%= link_to 'Atrás', slides_path %>
</div>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @slide.link %>
</p>

<p>
  <strong>Image:</strong>
  <%= @slide.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @slide.title %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>