config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :slides
  get 'admin/dashboard'

  devise_for :users
  
  get 'orders/create'

  resources :products
  #resources :users
  resources :orders

  root 'pages#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  post '/cart/add' => 'cart#add'

  get '/sincronizar' => 'products#sincronizar'
  get '/sincronizarupdate' => 'products#sincronizarupdate'
  get '/dashboard' => 'admin#dashboard'
  get '/cuenta' => 'pages#account'
  get '/verificar' => 'pages#verificar'
  get '/newcustomer' => 'pages#newcustomer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/dashboard.html.erb
<% provide(:page_title, 'Dashboard') %>
<% provide(:dashboard_active, 'active') %>
<% provide(:page_description, 'Bienvenido a Ofimaster, multitud de productos y marcas a tu disposición.') %>

<%#= link_to "current_user_show", current_user %>
<h1>Dashboard</h1>

<div class="row">
  <div class="col-12 col-sm-4">
    <p class="display-4 bg-primary text-center text-white py-3">
      Pedidos
      <strong><%= @orders.count %></strong>
    </p>
  </div>
  <div class="col-12 col-sm-4">
    <p class="display-4 bg-primary text-center text-white py-3">
      Usuarios
      <strong><%= @users.count %></strong>
    </p>
  </div>
  <div class="col-12 col-sm-4">
    <p class="display-4 bg-primary text-center text-white py-3">
      Productos
      <strong><%= @products.count %></strong>
    </p>
  </div>
</div>

<%= link_to 'Slides', slides_path %>
<%= link_to 'Agregar Post', new_post_path, :class => "btn btn-primary" %>
<%#= link_to 'New Product', new_product_path, :class => "btn btn-success" %>
<%#= link_to 'Crear Cuenta', new_user_registration_path, :class => 'btn btn-outline-primary' %>
<%= link_to 'Editar Cuenta', edit_user_registration_path, :class => 'btn btn-outline-primary' %>