config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :slides
  get 'admin/dashboard'

  devise_for :users
  
  get 'orders/create'

  resources :products
  #resources :users
  resources :orders

  root 'pages#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  post '/cart/add' => 'cart#add'

  get '/sincronizar' => 'products#sincronizar'
  get '/sincronizarupdate' => 'products#sincronizarupdate'
  get '/dashboard' => 'admin#dashboard'
  get '/cuenta' => 'pages#account'
  get '/verificar' => 'pages#verificar'
  get '/newcustomer' => 'pages#newcustomer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	def self.search(search)
	    if search
	      Product.where("(discontinued = 'false' AND unitprice > 0) AND code ILIKE ? OR description ILIKE ? OR familyname ILIKE ? OR notes ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").order(:familyname)
	    else
	      Product.all.where("discontinued = 'false' AND unitprice > 0").order(:unitprice)
	    end
	end

	#productos relacionados
	scope :relacionados, ->(product) { where("familyname = ?", product.familyname).order("RANDOM()").first(3) }

	

	after_create :update_slug
	before_update :assign_slug

	def to_param
		slug
	end

	private

	def assign_slug
		self.slug = "#{code.parameterize}"
	end

	def update_slug
		update_attributes slug: assign_slug
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :sincronizar, :sincronizarupdate]

  def sincronizar
    api_key = HTTParty.post('https://erp.laudus.cl/api/users/login?user=ibarrios&password=ibarrios&companyVatId=78307160-6', :headers => {'Accept' => 'application/json'})

    token = JSON.parse api_key.body

    products = HTTParty.get(
        'https://erp.laudus.cl/api/products/get/list/complete', 
        :headers => token
    )

    products_parse = JSON.parse products.body

    products_parse.each do |product|
      Product.create(
        productid:          product["productId"], 
        code:               product['code'], 
        description:        product['description'], 
        familyid:           product['familyId'], 
        familyname:         product['familyName'], 
        unitprice:          product['unitPrice'], 
        unitpricewithtaxes: product['unitPriceWithTaxes'], 
        discontinued:       product['discontinued'], 
        barcode:            product['barcode'], 
        unit:               product['unit'], 
        notes:              product['notes']
      )
    end
    redirect_to root_path
  end


  def sincronizarupdate
    api_key = HTTParty.post('https://erp.laudus.cl/api/users/login?user=ibarrios&password=ibarrios&companyVatId=78307160-6', :headers => {'Accept' => 'application/json'})

    token = JSON.parse api_key.body

    products = HTTParty.get(
        'https://erp.laudus.cl/api/products/get/list/complete', 
        :headers => token
    )

    products_parse = JSON.parse products.body

    products_parse.each do |product|
      p = Product.find_by(code: product['code'].to_s)
      p.productid           = product["productId"]
      p.code                = product['code']
      p.description         = product['description']
      p.familyid            = product['familyId']
      p.familyname          = product['familyName']
      p.unitprice           = product['unitPrice']
      p.unitpricewithtaxes  = product['unitPriceWithTaxes']
      p.discontinued        = product['discontinued']
      p.barcode             = product['barcode']
      p.unit                = product['unit']
      p.notes               = product['notes']
      p.save
    end
    redirect_to root_path
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.page(params[:page]).search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @relacionados = Product.relacionados(@product)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:photo, :productid, :code, :slug, :description, :familyid, :familyname, :unitprice, :unitpricewithtaxes, :discontinued, :barcode, :notes, :unit)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-12 col-sm-3">
      <div class="product-img">
        <%= image_tag @product.photo.medium.url, :class => "img-fluid d-block m-auto" %>
      </div>
      <div class="field form-group">
        <%= f.label :photo, 'Imagen' %>
        <%= f.file_field :photo, :class => "form-control" %>
      </div>
    </div>
    <div class="col-12 col-sm">
      <p class="lead">Código: <strong class="text-primary"><%= product.code %></strong></p>
      <p class="lead">ProductID: <strong class="text-primary"><%= product.productid %></strong></p>
      <p class="lead">Código de Barras: <strong class="text-primary"><%= product.barcode %></strong></p>
      <% if product.notes? %>
      <p class="lead">Marca: <strong class="text-primary"><%= product.notes %></strong></p>
      <% end %>
      <p class="lead">Categoría: <strong class="text-primary"><%= product.familyname %></strong></p>
      <p class="lead">
        Precio: <strong class="text-primary">
        <%= number_to_currency(product.unitprice.to_i, unit: "$", separator: ",", delimiter: ".", precision: 0, locale: :en) %>
        </strong>
      </p>
      <p class="lead">Descontinuado: <strong class="text-primary"><%= product.discontinued %></strong></p>
    </div>
    </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>
  
    <%#= f.label :productid %>
    <%#= product.productid %>
  
    <%#= f.label :code %>
    <%#= f.text_field :code %>
  
    <%#= f.label :description %>
    <%#= f.text_field :description %>
  
    <%#= f.label :familyid %>
    <%#= f.text_field :familyid %>
  
    <%#= f.label :familyname %>
    <%#= f.text_field :familyname %>
  
    <%#= f.label :unitprice %>
    <%#= f.number_field :unitprice %>
  
    <%#= f.label :unitpricewithtaxes %>
    <%#= f.number_field :unitpricewithtaxes %>
  
    <%#= f.label :barcode %>
    <%#= f.text_field :barcode %>
  
    <%#= f.label :notes %>
    <%#= f.text_field :notes %>
  
    <%#= f.label :discontinued %>
    <%#= f.check_box :discontinued %>

app/views/products/edit.html.erb
<% provide(:page_title, 'Editar Producto') %>
<% provide(:edit_product_active, 'active') %>

<div class="container">
<h1>Editar <%= @product.description.split(' - ', 2).last %></h1>

<%= render 'form', product: @product %>

<%= link_to 'Ver', @product %> |
<%= link_to 'Atrás', products_path %>
</div>

app/views/products/index.html.erb
<% provide(:page_title, 'Productos') %>
<% provide(:root_active, 'active') %>
<% provide(:page_description, 'Bienvenido a Ofimaster, multitud de productos y marcas a tu disposición.') %>

<% if notice %>
  <div class="alert alert-success fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong><%= notice %></strong>
  </div>
<% end %>

<button type="button" class="btn btn-primary w-100 mb-2 hidden-md-up" data-toggle="offcanvas">Categorías</button>
<div class="row justify-content-md-center row-offcanvas row-offcanvas-left">
  <div class="col-8 col-sm-6 col-md-3 col-lg-2 sidebar-offcanvas">
    <%= render 'layouts/nav-sidebar' %>
  </div>
  <div class="col col-md-9">
    <% if @products.empty? %>
      <p class="lead">Sin productos en esta categoría</p>
    <% else %>
      <%= form_tag("/cart/add", method: :post) do %>
        <table class="table table-hover table-sm table-responsive">
          <thead>
            <tr>
              <th>Imagen</th>
              <th>Código</th>
              <th>Descripción</th>
              <th>Categoría</th>
              <th>Marca</th>
              <% if user_signed_in? %>
                <th>Precio</th>
              <% end %>
              <th class="table-quantity">Cantidad</th>
            </tr>
          </thead>
          <tbody>
            <% count = 1 %>
            <% @products.each do |product| %>
                <tr>
                  <td>
                    <%= image_tag product.photo.thumb.url %>
                  </td>
                  <td>
                    <%= link_to product do %>
                      <%= product.code %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to product do %>
                      <%= product.description.split(' - ', 2).last %>
                    <% end %>
                  </td>
                  <td>
                    <% if product.familyname %>
                      <%= link_to product.familyname, "/products?search=#{product.familyname.gsub(" ", "+")}" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to product.notes, "/products?search=#{product.notes}" %>
                  </td>
                  <% if user_signed_in? %>
                    <td class="text-right">
                      <%= number_to_currency(product.unitprice.to_i, unit: "$", separator: ",", delimiter: ".", precision: 0, locale: :en) %>
                    </td>
                  <% end %>
                  <td>
                    <%= hidden_field_tag "id#{count}", product.productid %>
                    <%= text_field_tag "quantity#{count}", nil, :class => 'form-control' %>
                  </td>
                </tr>
              <% count+=1 %>
            <% end %>
          </tbody>
        </table>
        <div class="row justify-content-between">
          <div class="col">
            <%= paginate @products %>
          </div>
          <div class="col-4 col-sm-3 col-lg-2">
            <%= button_tag '', :class => 'btn btn-primary' do %>
              Agregar al 
              <span class="fa fa-shopping-cart"></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:page_title, 'Nuevo Producto') %>
<% provide(:new_product_active, 'active') %>

<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% provide(:page_title, @product.code) %>
<% provide(:page_description, @product.description) %>
<p id="notice"><%= notice %></p>
<button type="button" class="btn btn-primary w-100 mb-2 hidden-md-up" data-toggle="offcanvas">Categorías</button>
<div class="row justify-content-md-center row-offcanvas row-offcanvas-left">
  <div class="col-8 col-sm-6 col-md-3 col-lg-2 sidebar-offcanvas">
    <%= render 'layouts/nav-sidebar' %>
  </div>
  <div class="col col-md-9">
    <div class="row">
      <div class="col-12 col-sm-3">
        <div class="product-img">
          <%= link_to '', edit_product_path(@product), :class => 'fa fa-pencil btn btn-warning btn-sm product-edit' %>
          <%= image_tag @product.photo.medium.url, :class => "img-fluid d-block m-auto" %>
        </div>
      </div>
      <div class="col-12 col-sm-9">
        <p class="lead">
          <strong><%= @product.description.split(' - ', 2).last %></strong>
        </p>
        <p class="lead">Código: <strong class="text-primary"><%= @product.code %></strong></p>
        <% if @product.notes? %>
        <p class="lead">Marca: <strong class="text-primary"><%= @product.notes %></strong></p>
        <% end %>
        <p class="lead">Categoría: <strong class="text-primary"><%= @product.familyname %></strong></p>
        <p class="lead">
          Precio: <strong class="text-primary">
          <%= number_to_currency(@product.unitprice.to_i, unit: "$", separator: ",", delimiter: ".", precision: 0, locale: :en) %>
          </strong>
        </p>
      </div>
    </div>
    

    <p class="lead"><strong>Productos en la misma categoría</strong></p>
    <div class="row justify-content-center">
      <% @relacionados.each do |producto| %>
      <div class="col-12 col-sm-6 col-md-4 my-1">
        <div class="d-flex flex-row align-items-center producto-relacionado">
          <%= image_tag producto.photo.medium.url, :class => "img-fluid" %>
          <%= link_to producto.description.split(' - ', 2).last, producto, :class => "pl-2" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>