config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :slides
  get 'admin/dashboard'

  devise_for :users
  
  get 'orders/create'

  resources :products
  #resources :users
  resources :orders

  root 'pages#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  post '/cart/add' => 'cart#add'

  get '/sincronizar' => 'products#sincronizar'
  get '/sincronizarupdate' => 'products#sincronizarupdate'
  get '/dashboard' => 'admin#dashboard'
  get '/cuenta' => 'pages#account'
  get '/verificar' => 'pages#verificar'
  get '/newcustomer' => 'pages#newcustomer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="jumbotron bg-inverse text-white mt-3 mb-0 py-3">
	<div class="row">
		<div class="col-12 col-sm-4 mb-3">
			<%= image_tag "/images/logo-ofimaster-blanco.png", :class => "d-block img-fluid" %>

			<small>Comercializamos y distribuimos productos y servicios de aseo, artículos de oficina y maquinaria, entre otros, para el mercado público y privado, institucional e industrial, de forma eficiente y especializada. Contamos con Certificación ISO 9001:2008, lo que garantiza seriedad y eficacia en la venta, pero también una post venta responsable.</small>
		</div>
		<div class="col-12 col-sm-4 mb-3">
			<small>CASA MATRIZ</small>
			<p class="lead mb-0"><strong>PUERTO VARAS</strong></p>
			<small>Caletera Poniente KM 1006 Ruta 5 Sur. <span>Tel: +56 (65) 2 317 720</span></small>
		
			<hr class="line">
		
			<small>SUCURSAL</small>
			<p class="lead mb-0"><strong>OSORNO</strong></p>
			<small>Manuel Antonio Matta #549, Oficina 906. <span>Tel: +56 (65) 2 314 010</span></small>
		</div>
		<div class="col-12 col-sm-4 mb-3">
			<small><strong>Aviso Legal</strong></small><br>
			<small>Queda prohibida la reproducción total o parcial de cualquier material de caracter gráfico expuesto en este sitio web, por cualquier medio o procedimiento, sin para ello contar con la autorización previa, expresa y por escrito de Ofimaster Limitada. Toda forma de utilización de nuestro material no autorizada será perseguida con lo establecido en la ley de protecciòn a la propiedad intelectual. © Todos Derechos Reservados Ofimaster Limitada.</small>
		</div>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse mb-2 align-items-center">
  <a class="navbar-brand hidden-md-up" href="#">
    <%= image_tag "/images/logo-ofimaster-blanco.png", :class => "logo" %>
  </a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-around align-items-center" id="navbarTop">
    <a class="navbar-brand hidden-sm-down" href="/">
      <%= image_tag "/images/logo-ofimaster-blanco.png", :class => "logo" %>
    </a>
    <%= form_tag products_path, :class => '', :method => 'get' do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Buscar...', :required => true %>
      <span class="input-group-btn">
        <button class="btn btn-outline-secondary" type="submit">
        <span class="fa fa-search"></span>
        </button>
      </span>
    </div>
    <% end %>
    <ul class="navbar-nav mt-2 mt-lg-0">
      <li class="nav-item <%= yield(:root_active) %>">
        <%= link_to 'Inicio', root_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item <%= yield(:posts_active) %>">
        <%= link_to 'Noticias', posts_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item <%= yield(:cart_active) %>">
        <%= link_to 'Carro', cart_path, :class => 'nav-link' %>
      </li>
      <% unless user_signed_in? %>
        <li class="nav-item <%= yield(:new_session_active) %>">
          <%= link_to 'Ingresar', new_user_session_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item <%= yield(:new_user_active) %>">
          <%= link_to 'Registrar', new_user_registration_path, :class => 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item <%= yield(:orders_active) %>">
          <%= link_to 'Pedidos', orders_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item <%= yield(:cuenta_active) %>">
          <%= link_to 'Cuenta', cuenta_path, :class => 'nav-link', data: { turbolinks: false } %>
        </li>
        <li class="nav-item <%= yield(:dashboard_active) %>">
          <%= link_to 'Dashboard', dashboard_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, :class => 'nav-link nav-link-logout' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title><%= yield(:page_title) %> | Ofimaster</title>
    <meta name="description" content="<%= yield(:page_description) %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>    
    <div class="container-fluid alto-minimo">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>